# Generated by Django 5.2.17 on 2026-09-09 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('customer_segment', models.CharField(max_length=50)),
                ('signup_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='api.cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('payment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='api.pedido')),
            ],
        ),
    ]
