# Generated by Django 5.2.17 on 2026-09-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='signup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
